// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBON4JK_UxmkUP_ZjZdoUBPgoRwhJ1jW4A',
    appId: '1:556715220579:web:23103b4742964a5b7d2256',
    messagingSenderId: '556715220579',
    projectId: 'nongskuy-8a5d6',
    authDomain: 'nongskuy-8a5d6.firebaseapp.com',
    storageBucket: 'nongskuy-8a5d6.appspot.com',
    measurementId: 'G-S1J19KL6L7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4UhaKrWlZaPl_2MwuTAF-XQBbMshwWCE',
    appId: '1:556715220579:android:776773979e7e1bbb7d2256',
    messagingSenderId: '556715220579',
    projectId: 'nongskuy-8a5d6',
    storageBucket: 'nongskuy-8a5d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANDUSKc22tgb7JctYg9DOinvyLwSRfKqg',
    appId: '1:556715220579:ios:68409b45eead7d827d2256',
    messagingSenderId: '556715220579',
    projectId: 'nongskuy-8a5d6',
    storageBucket: 'nongskuy-8a5d6.appspot.com',
    iosClientId: '556715220579-ldv7tre4sfa2dm5210ll01tbh872c3mr.apps.googleusercontent.com',
    iosBundleId: 'com.example.asynchronousCoffe',
  );
}
